### ISSUE TITLE
[Level] Letter Collecting

### ISSUE THREAD

**Issue by cKellyDesign** [cKellyDesign/BusyBeeSpelling#10]
When tapping a letter within a level, BusyBee should animate over to the position of the letter and display feedback as to whether or not the letter is a valid answer for that level. 
### On Tap
- [ ] Positioning - BusyBee should position itself directly over the letter, currently it is too low
- [x] Feedback Triggering Timing - Currently a second tap is required, needs to do so after BusyBee positions itself
### On Correct
- [x] Feedback bee animates to hive - no panel
- [ ] Success Sound - there should be a success sound and audio re the letter
- [x] Animate letter to Hive, down Tube, into Correct Letters Area
- [x] Display Points
- [x] Animate Undulation of Hive Tube
- [x] after letter appears in correct area, play continues
### On Wrong
- [ ] Fail Sound - there should be a fail sound
- [x] Remove the letter
- [x] screen overlay panel happens 
- [x] sound that lets users hear the answer and tells them it isn't correct

**Comment by cKellyDesign** [comment]
@dooderlani - Hey Beth, lets triage a solution to animate busyBee taking a correct answer to the hive. I'm just running into a bit of a roadblock animating the scrolling of the window to actually follow the letter and bee over to the hive. I think we'll have to do this with CSS animations or something because this AngularJS framework doesn't seem to be very good at this particular type of thing :-/  I think we can come up with a good solution but definitely wanted to brainstorm something with you!

**Comment by HaYesSeattle** [comment]
cool - ya maybe the hive can follow along with the scroll like the menu and answers do? and we can add an animation class to the honey tube for 5 seconds or something?

**Comment by HaYesSeattle** [comment]
@cKellyDesign - I made the bee smaller and it totally jacked up the positioning...sorry. :(

**Comment by cKellyDesign** [comment]
### TODO
- [ ] add class for digraphs to effect font-size

**Comment by HaYesSeattle** [comment]
these are duplicates - closing this issue
