### ISSUE TITLE
Final push - scripting

### ISSUE THREAD

**Issue by HaYesSeattle** [cKellyDesign/BusyBeeSpelling#34]
LEVEL 
- [x] Level Complete Functionality - on success, should be success screen and then another game of the same level. On 3 successes, user moves to next level #36 
- [x] On level non-mastery (we're all winners) => similar levels (in difficulty)
- [x] If more than one incorrect answer repeat level difficulty #36
- [x] Cap correct answers at 5 per level, generate non-correct options until 8
- [x] Multiple Focus in single level - lowercase vowels, uppercase vowels, ect. #36
- [x] Launch into Vowels
- [x] Loading screen - After App Starts up Before AngularJS finishes loading #53 
- [ ] Level complete message screen logic in #53, just needs markup!
- [x] need to add sound: "look for" "[num]" JS listener on html5 audio #53
     http://stackoverflow.com/questions/6312714/adding-event-listener-to-audio-html5-tag-in-javascript
- [x] select level functionality #53
- [ ] bee and letter move to hive with right letter click (if easy) 
- [x] Sound angular js - sounds will be hear on: 
    loading screen, incorrect pop up, title screen, onCorrect answer
- [x] Make zoom variables for click handler equations - #42 
- [x] Do menu slide animation via classes applied by jQuery within BusyBeeApp.js #43 
- [x] Randomize Challenges within Levels (keep track!) #44

notes:
 v1 -Never ending game! Keep track of "score"
 vN - add different kinds of levels (making words, other languages, shapes, sky = limit!)
- [ ] Ability to build a word - final level
- [ ] Menu hook up for click on level

**Comment by HaYesSeattle** [comment]
![wfs-bigpic-flow-r2](https://cloud.githubusercontent.com/assets/3664500/10356594/9db845f6-6d2d-11e5-891e-a4de2a0bf56d.png)
![wfs-bigpic-play-flow](https://cloud.githubusercontent.com/assets/3664500/10356651/25d3c6e0-6d2e-11e5-8546-53d8016b3942.png)

![wfs-initial-flow-r2](https://cloud.githubusercontent.com/assets/3664500/10356623/e14f83a6-6d2d-11e5-9eb4-298f35744e2c.png)
![wfs-play-flow](https://cloud.githubusercontent.com/assets/3664500/10356595/9dba182c-6d2d-11e5-8a8c-2d4808ab8022.png)

**Comment by cKellyDesign** [comment]
@dooderlani - Hey do you think we can outline what all the level difficulties and combos should be? Are you thinking something like this?
1. find vowels (all lowercase)
2. find vowels (lowercase / uppercase mix)
3. find uppercase vowels (lowercase / uppercase mix)
4. find consonants (all uppercase)  
5. etc...
6. etc...

The logic to track and progress through the levels will be pretty easy as long as we know what to generate!

**Comment by cKellyDesign** [comment]
@dooderlani - Did we say 2 or 3 wrong answers for non-mastery? I totally forget!

**Comment by HaYesSeattle** [comment]
@cKellyDesign - sounds good - I can create some logic doc - or just edit/ add to your list above
they can get unlimited wrong answers during the play... In a level, we were thinking if they got 100% right 3x then they would move up in difficulty.

we were also thinking a level would consist of a couple games of different topics -- 
ex: Level 1: uppercase vowels and uppercase consonants
Level 2: lowercase vowels and lowercase consonants

...I will whip something up.

**Comment by HaYesSeattle** [comment]
@cKellyDesign 

How does this level progression look? Let me know if these are too difficult to pull off or you think there is a better way.

Level 1 challenges: 
    Vowels:   
                show only uppercase vowels 
        show only lowercase vowels
    Consonants   
                show only uppercase consonants
        show only lowercase consonants

reward screen — then — move to level 2 when each of these challenges has 3 successes with no wrong answers -

Level 2 challenges
    Vowels:   show mixture of uppercase and lowercase vowels
    Consonants:   show mixture of uppercase and lowercase consonants

reward screen — then — move to level 3 when each of these challenges has 3 successes with no wrong answers

Level 3 challenges
    Diagraphs:    show digraphs — st, sh, ch, th, wh, ph, ee, ea, ow, ng, ck 
    Consonants:   show mixture of uppercase and lowercase consonants
    Vowels:       show mixture of uppercase and lowercase consonants
    Blends:     show blends — Fl, bl, sl, cl, pl, bl, gr, tr, br, cr, dr, pr, fr, wh, str, sw, sp, sc, sn, sm, sk

reward screen — then — move to level 4 when each of these challenges has 3 successes with no wrong answers

level 4 challenges:
    build a 3 letter word:
        show answer/ word greyed out in answer area — diagraphs and blends are shown with vowels and consonants as possible answers
                - or - 
        build any word — show vowels, consonants, diagraphs and blends - user can click on any of these and form a word in the answer space

reward screen — then — move to level 5 when challenge has 3 successes with no wrong answers

level 5 challenges:
    build a 4 letter word:
        show answer/ word greyed out in answer area — diagraphs and blends are shown with vowels and consonants as possible answers
                - or - 
        build any word — show vowels, consonants, diagraphs and blends - user can click on any of these and form a word in the answer space

reward screen — then — move to level 6 when challenge has 3 successes with no wrong answers

level 6 challenges:
    build a 5 letter word:
        show answer/ word greyed out in answer area — diagraphs and blends are shown with vowels and consonants as possible answers
                - or - 
        build any word — show vowels, consonants, diagraphs and blends - user can click on any of these and form a word in the answer space

reward screen — then — move to infinite loop level 7 when challenge has 3 successes with no wrong answers

level 7 challenges:
    build a 3-5 letter word:
        show answer/ word greyed out in answer area — diagraphs and blends are shown with vowels and consonants as possible answers
                - or - 
        build any word — show vowels, consonants, diagraphs and blends - user can click on any of these and form a word in the answer space

**Comment by HaYesSeattle** [comment]
@cKellyDesign - is it possible to move the bee with the correct answer to the hive? I think that would help the user be patient while the game pauses for the letter collection.

also - it would be cool if the bee stayed visible with the swipe - I tried working on this but just broke stuff. Here was my trail...
http://stackoverflow.com/questions/20253322/angular-js-scroll-window
http://stackoverflow.com/questions/14878761/bind-class-toggle-to-window-scroll-event
