### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by HaYesSeattle** [cKellyDesign/BusyBeeSpelling#52]
all
- [x] touch area needs to be bigger  FIXED
- [x] remove menu  FIXED
- [x] should see bee on launch?
- [x] add help button to remind people what they are looking for FIXED - added sound on wrong answer
- [ ] bee needs to be centered over touch... again -- or maybe it is better it is off so the letter is still clickable?
- [x] test: letter touch buggy if another flower is close by, bee sometimes gets in the way #61 
- [x] game ends...it should never end - should go into random play  @cKellyDesign  #60
- [ ] on game end it plays only blends - should go into random play of more topics @cKellyDesign 

android 
- [x] code shows up for a while on title screen #62
- [x] error screen wraps too much #61
- [x] pollen spore sometimes goes off top of screen, on big yellow flower #61
- [ ]  intro sound and incorrect answer sound - fixed need to TEST android #57 (comments below)
- [x] answer area, error screen moves on swipe (jellybean) 
    notes: they move the exact same distance even though they are different unrelated/ nested divs -- seems to be related to how far you swipe - if swipe back to left and touch it shows in right spot.
  **the fixed hive layer however has no issues... FIXED
- [x]  <  jellybean > refreshes constantly when phonegap desktop server is on

iphone
- [ ] splash screen not showing - https://github.com/apache/cordova-plugin-splashscreen
- [x] vertical scrolling - goes no where, but find a way to prevent movement - http://stackoverflow.com/questions/16274074/stopping-overscroll-bounce-in-phonegap-ios

**Comment by HaYesSeattle** [comment]
@cKellyDesign - do you think this is the issue? seems odd that it loads images but not sound.
http://community.phonegap.com/nitobi/topics/media-plugin-in-phonegap-build

here is another android specific issue: http://stackoverflow.com/questions/27901757/playing-wav-file-in-phonegap
http://stackoverflow.com/questions/12657341/phonegap-not-able-to-play-local-sound-file

https://chrisgriffith.wordpress.com/2014/04/01/edge-animate-phonegap-build/

http://stackoverflow.com/questions/21968455/cordova-media-capture-android-error-no-3-issue

Solution for iphone was to add:
< plugin name="org.apache.cordova.media" />

**Comment by HaYesSeattle** [comment]
oy @cKellyDesign  - I think I found the solution...
we need to use the media plugin:
http://stackoverflow.com/questions/21638741/html5-audio-not-playing-in-phonegap-app-possible-to-use-media

but I tried just that and it wasnt working.

It might have to be on click? because there are other issues with old browsers...Audio Streams will Not Load in Mobile Browsers

When the webpage loads, mobile browsers (Safari/Chrome in iOS 6 and below and Chrome in Android – jelly bean) do not download the audio streams, unless the user initiates an action like onclick or ontouchstart. They simply keep the audio files pending (checked in dev tools network tab in android).

Hence, this piece of code would do nothing on the aforementioned mobile browsers (will be just silent) while play fine on desktop browsers:

var audio = document.querySelector('audio#game_music');
audio.play();
Features like preload and autoplay (as attributes in the audio tag) don’t work either. Sad.

## Emulating clicks, i.e., play()ing inside click event handlers is not a solution either.

and then there is this:
http://codetheory.in/solve-your-game-audio-problems-on-ios-and-android-with-web-audio-api/
